// CYBER ARCADE hub strings {key: [zh-HK, en]} — cyber-kit v0.2.1 i18n (vendor/cyber-kit/core/i18n.js).
import { i18n } from '../vendor/cyber-kit/core/i18n.js';
i18n.add({
  'doc.title': ['CYBER ARCADE 賽博街機', 'CYBER ARCADE'],
  kicker: ['NEON KOWLOON · GAME HUB', 'NEON KOWLOON · GAME HUB'], sub: ['賽博街機 · 一個 App 玩晒全部遊戲', 'Every CYBER game in one app'],
  yourTier: ['你嘅級別', 'YOUR TIER'], unlock: ['解鎖', 'UNLOCK'], store: ['解鎖更多遊戲', 'UNLOCK MORE GAMES'],
  'tier.free': ['免費', 'FREE'], 'tier.silver': ['銀級', 'SILVER'], 'tier.gold': ['金級', 'GOLD'],
  'badge.free': ['免費 FREE', 'FREE'], 'badge.silver': ['銀 SILVER', 'SILVER'], 'badge.gold': ['金 GOLD', 'GOLD'],
  adsOn: ['免費版：只喺完局等自然停頓位先會有廣告', 'Free: ads only at natural breaks (e.g. game over)'], adsOff: ['已移除強制廣告 · 獎勵廣告仍然係自選', 'Forced ads removed · rewarded ads stay optional'],
  play: ['開始玩', 'PLAY'], tryIt: ['試玩', 'TRY'], unlocked: ['已解鎖', 'UNLOCKED'], locked: ['未解鎖', 'LOCKED'],
  trialLeft: ['試玩 · 今日剩 {n}/{max} 次', 'TRIAL · {n}/{max} left today'], trialNone: ['今日試玩已用完', 'No trials left today'],
  trialTitle: ['{tier}遊戲試玩', '{tier} GAME TRIAL'], trialBody: ['「{name}」屬於{tier}。免費玩家每日可以試玩 {max} 次，今日仲有 {n} 次。', '"{name}" is a {tier} game. Free players get {max} trial runs a day — {n} left today.'],
  trialRule: ['試玩規則：{rule}', 'Trial rule: {rule}'], startTrial: ['開始試玩', 'START TRIAL'], cancel: ['取消', 'CANCEL'], close: ['關閉', 'CLOSE'],
  exhausted: ['「{name}」今日 {max} 次試玩已經用完。聽日再嚟，或者解鎖{tier}即刻無限玩。', 'You have used all {max} trial runs of "{name}" today. Come back tomorrow, or unlock {tier} to play without limits.'],
  storeTitle: ['揀你嘅級別', 'CHOOSE YOUR TIER'], storeSub: ['一次性購買 · 唔係訂閱', 'One-time purchase · not a subscription'],
  includes: ['包括', 'INCLUDES'], freeGames: ['免費遊戲', 'Free games'], current: ['目前級別', 'CURRENT'], owned: ['已擁有', 'OWNED'], included: ['已包括', 'INCLUDED'],
  buy: ['購買 {price}', 'BUY {price}'], upgrade: ['升級 {price}', 'UPGRADE {price}'], upgradeNote: ['你已經有銀級，補差價 {price} 就升金級', 'You own Silver — upgrade to Gold for {price}'],
  'feat.freeGames': ['免費遊戲任玩', 'All free games, unlimited'], 'feat.trial': ['銀級／金級遊戲每日 3 次試玩', '3 daily trial runs of Silver/Gold games'],
  'feat.adsNatural': ['有廣告（只喺完局等自然停頓位）', 'Ads at natural breaks only (e.g. game over)'], 'feat.rewarded': ['獎勵廣告：自選，用嚟復活／復原', 'Rewarded ads: optional, for continue / undo'],
  'feat.silverGames': ['解鎖全部銀級遊戲', 'Unlock every Silver game'], 'feat.noForced': ['移除所有強制／插頁廣告', 'No forced / interstitial ads'],
  'feat.silverFuture': ['包括日後加入銀級嘅所有新遊戲', 'Includes every future game added to Silver'],
  'feat.goldAll': ['包括銀級全部內容', 'Everything in Silver'], 'feat.goldGames': ['解鎖全部金級遊戲', 'Unlock every Gold game'],
  'feat.goldFuture': ['包括日後加入銀級或金級嘅所有新遊戲', 'Includes every future Silver or Gold game'],
  fine: ['一次性購買，唔係訂閱。解鎖會綁定你嘅 Google Play 帳戶，只要呢個 App 仍然喺 Google Play 提供，你都可以喺任何 Android 裝置用「恢復購買」取回。價格以 Google Play 顯示為準，各地區可能不同。', 'One-time purchase, not a subscription. Your unlock is tied to your Google Play account and can be restored on any Android device with "Restore purchases" for as long as this app is offered on Google Play. Prices are shown by Google Play and may vary by country.'],
  restore: ['恢復購買', 'RESTORE PURCHASES'], restored: ['已恢復：{tier}', 'Restored: {tier}'], restoreNone: ['搵唔到購買紀錄（目前：免費）', 'No purchases found (current tier: Free)'], restoreFail: ['恢復失敗，請稍後再試', 'Restore failed, please try again later'],
  bought: ['已解鎖{tier}！多謝支持 ♥', '{tier} unlocked — thank you! ♥'], buyCancelled: ['已取消購買', 'Purchase cancelled'], buyFail: ['購買失敗：{err}', 'Purchase failed: {err}'],
  stubTag: ['DEV 模擬付款 · 唔會收錢', 'DEV STUB · NO REAL PAYMENT'], stubTitle: ['模擬 Google Play 付款', 'Simulated Google Play payment'],
  stubBody: ['呢個係網頁原型嘅模擬付款（DEV STUB），唔會收任何費用。正式 App 會用 Google Play Billing。', 'This is a simulated payment in the web prototype (DEV STUB). Nothing is charged. The real app uses Google Play Billing.'],
  stubConfirm: ['確認（模擬）', 'CONFIRM (SIMULATED)'],
  'prod.tier_silver': ['銀級解鎖', 'Silver unlock'], 'prod.tier_gold': ['金級解鎖', 'Gold unlock'], 'prod.tier_gold_upgrade': ['銀級升金級', 'Silver → Gold upgrade'],
  webNote: ['網頁版：所有遊戲喺網上都可以免費試玩。付費解鎖只適用於日後嘅 Google Play App；呢頁嘅購買全部係模擬（DEV STUB），唔會收錢。', 'Web build: every game stays free to try on the web. Paid unlocks apply to the upcoming Google Play app only; purchases on this page are simulated (DEV STUB) and never charge you.'],
  footer: ['未公開頁面 · 唔會被搜尋器收錄', 'Unlisted · not indexed'],
  loading: ['載入中…', 'Loading…'], fail: ['載入 games.json 失敗', 'Failed to load games.json'],
  dev: ['DEV 工具（模擬）', 'DEV TOOLS (STUB)'], devReset: ['重設購買（模擬帳戶 + 本機）', 'Reset purchases (stub account + cache)'], devTrials: ['重設今日試玩', "Reset today's trials"],
  devWipe: ['清除本機紀錄（模擬重新安裝）', 'Wipe local cache (simulate reinstall)'], devSilver: ['模擬：擁有銀級', 'Simulate: own Silver'], devGold: ['模擬：擁有金級', 'Simulate: own Gold'],
  devBackend: ['付款後端：{id}', 'Billing backend: {id}'],
  launching: ['開緊「{name}」…', 'Launching "{name}"…'],
  demo: ['示範', 'DEMO'], thumbAlt: ['「{name}」遊戲畫面', '{name} gameplay screenshot'], stage: ['進度', 'STAGE'],
  trialOver: ['「{name}」試玩到此為止。解鎖{tier}就可以玩晒全部地圖同無盡模式。', 'That is the end of the "{name}" trial. Unlock {tier} to play every map and the full endless mode.'],
});
export { i18n };
